"""VendorInterface model: add processing_options

Revision ID: 274ed33dae43
Revises: 991306da2f56
Create Date: 2023-05-17 09:58:01.771048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274ed33dae43'
down_revision = '991306da2f56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_interfaces', sa.Column('processing_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_interfaces', 'processing_options')
    # ### end Alembic commands ###
