"""Remove has_active_vendor_interfaces

Revision ID: 310b31225b9d
Revises: 1d954292be5e
Create Date: 2023-06-05 09:27:14.956787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310b31225b9d'
down_revision = '1d954292be5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'has_active_vendor_interfaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('has_active_vendor_interfaces', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
