"""Add folio_job_execution_uuid

Revision ID: 325a951f65c7
Revises: 0ba6b75cc77a
Create Date: 2023-05-16 10:01:40.057018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325a951f65c7'
down_revision = '0ba6b75cc77a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_data_loads', sa.Column('folio_job_execution_uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_data_loads', 'folio_job_execution_uuid')
    # ### end Alembic commands ###
