"""Remove unique constraint on folio_data_import_profile_uuid

Revision ID: 35ba6262f0a0
Revises: 338ba062b8f4
Create Date: 2023-05-11 09:15:40.859560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ba6262f0a0'
down_revision = '338ba062b8f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendor_interfaces_folio_data_import_profile_uuid_key', 'vendor_interfaces', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vendor_interfaces_folio_data_import_profile_uuid_key', 'vendor_interfaces', ['folio_data_import_profile_uuid'])
    # ### end Alembic commands ###
