"""Remove uniqueness contraint from Vendor.display_name

Revision ID: 46c754d079ce
Revises: 9671879df3f4
Create Date: 2023-05-30 16:13:24.505401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c754d079ce'
down_revision = '9671879df3f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendors_display_name_key', 'vendors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vendors_display_name_key', 'vendors', ['display_name'])
    # ### end Alembic commands ###
