"""Adds note to VendorInterface

Revision ID: 518b3d98f625
Revises: 910e6f44a08e
Create Date: 2025-11-19 10:23:44.968402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518b3d98f625'
down_revision = '910e6f44a08e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_interfaces', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_interfaces', 'note')
    # ### end Alembic commands ###
