"""add vendor_interface model

Revision ID: 55557ab268c9
Revises: 965229094874
Create Date: 2023-05-03 10:21:46.652162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55557ab268c9'
down_revision = '965229094874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('folio_interface_uuid', sa.String(length=36), nullable=False),
    sa.Column('folio_data_import_profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('folio_data_import_processing_name', sa.String(length=50), nullable=False),
    sa.Column('file_pattern', sa.String(length=250), nullable=True),
    sa.Column('remote_path', sa.String(length=250), nullable=True),
    sa.Column('processing_dag', sa.String(length=50), nullable=True),
    sa.Column('processing_delay_in_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio_data_import_profile_uuid'),
    sa.UniqueConstraint('folio_interface_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_interfaces')
    # ### end Alembic commands ###
