"""Increasing length of VendorInterface display_name

Revision ID: 5dc5da2d1d3c
Revises: 6fcfcb9d2ee4
Create Date: 2023-06-09 12:23:31.620928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc5da2d1d3c'
down_revision = '6fcfcb9d2ee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_interfaces', 'display_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=135),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_interfaces', 'display_name',
            existing_type=sa.VARCHAR(length=135),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False)
    # ### end Alembic commands ###
