"""Add loaded_history to VendorFile

Revision ID: 6ce07f19623f
Revises: 683e48ee4e57
Create Date: 2023-06-14 09:15:33.959470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce07f19623f'
down_revision = '683e48ee4e57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_files', sa.Column('loaded_history', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_files', 'loaded_history')
    # ### end Alembic commands ###
