"""Allowing null acquisitions_unit_from_folio

Revision ID: 6fcfcb9d2ee4
Revises: c20d54b0d230
Create Date: 2023-06-06 12:20:02.737686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcfcb9d2ee4'
down_revision = 'c20d54b0d230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'acquisitions_unit_from_folio',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'acquisitions_unit_from_folio',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
