"""add file model

Revision ID: 80041eebb354
Revises: 55557ab268c9
Create Date: 2023-05-04 14:52:46.809242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80041eebb354'
down_revision = '55557ab268c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('vendor_interface_id', sa.Integer(), nullable=True),
    sa.Column('vendor_filename', sa.String(length=250), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('vendor_timestamp', sa.DateTime(), nullable=True),
    sa.Column('loaded_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('not_fetched', 'fetching_error', 'fetched', 'loading', 'loading_error', 'loaded', name='filestatus'), server_default='not_fetched', nullable=False),
    sa.ForeignKeyConstraint(['vendor_interface_id'], ['vendor_interfaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
