"""Drop FileDataLoad model, add dag_run_id

Revision ID: 82368e89d0cb
Revises: 274ed33dae43
Create Date: 2023-05-18 14:27:53.085946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82368e89d0cb'
down_revision = '274ed33dae43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_data_loads')
    op.add_column('vendor_files', sa.Column('dag_run_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'vendor_files', ['dag_run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_files', type_='unique')
    op.drop_column('vendor_files', 'dag_run_id')
    op.create_table('file_data_loads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('vendor_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dag_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dag_run_starttime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dag_run_endtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('not_loaded', 'loading_error', 'loaded', name='dataloadstatus'), server_default=sa.text("'not_loaded'::dataloadstatus"), autoincrement=False, nullable=False),
    sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('folio_job_execution_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_file_id'], ['vendor_files.id'], name='file_data_loads_vendor_file_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_data_loads_pkey'),
    sa.UniqueConstraint('dag_run_id', name='file_data_loads_dag_run_id_key')
    )
    # ### end Alembic commands ###
