"""Adds new enum for File status

Revision ID: 910e6f44a08e
Revises: 9ad8c2163afc
Create Date: 2025-07-31 10:17:57.535054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910e6f44a08e'
down_revision = '9ad8c2163afc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE filestatus ADD VALUE 'empty_file_error'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DELETE FROM pg_enum
    WHERE enumlabel='empty_file_error'
    AND enumtypid= (
      SELECT oid FROM pg_type WHERE typname='filestatus'
    )""")
    # ### end Alembic commands ###
