"""Create vendors table

Revision ID: 965229094874
Revises: 
Create Date: 2023-05-01 14:45:09.973516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965229094874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('folio_organization_uuid', sa.String(length=36), nullable=False),
    sa.Column('vendor_code_from_folio', sa.String(length=36), nullable=False),
    sa.Column('acquisitions_unit_from_folio', sa.String(length=36), nullable=False),
    sa.Column('has_active_vendor_interfaces', sa.Boolean(), nullable=False),
    sa.Column('last_folio_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('folio_organization_uuid'),
    sa.UniqueConstraint('vendor_code_from_folio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    # ### end Alembic commands ###
