"""Add archive_date to vendor file

Revision ID: 9671879df3f4
Revises: 35c6cd1d594e
Create Date: 2023-05-25 12:52:21.108753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9671879df3f4'
down_revision = '35c6cd1d594e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_files', sa.Column('archive_date', sa.Date(), nullable=True))
    op.alter_column('vendor_files', 'expected_execution',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_files', 'expected_execution',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('vendor_files', 'archive_date')
    # ### end Alembic commands ###
