"""Add uploaded file status

Revision ID: 975b4e3f53f3
Revises: 58a045522fe5
Create Date: 2023-05-24 11:53:44.260981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975b4e3f53f3'
down_revision = '58a045522fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE filestatus ADD VALUE 'uploaded'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DELETE FROM pg_enum
    WHERE enumlabel='uploaded'
    AND enumtypid= (
      SELECT oid FROM pg_type WHERE typname='filestatus'
    )""")
    # ### end Alembic commands ###
