"""Add skipped file status

Revision ID: 991306da2f56
Revises: 325a951f65c7
Create Date: 2023-05-17 14:24:59.580198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991306da2f56'
down_revision = '325a951f65c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE filestatus ADD VALUE 'skipped'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DELETE FROM pg_enum
    WHERE enumlabel='skipped'
    AND enumtypid= (
      SELECT oid FROM pg_type WHERE typname='filestatus'
    )""")
    # ### end Alembic commands ###
