"""Increase size of data import processing name column

Revision ID: 9ad8c2163afc
Revises: 6ce07f19623f
Create Date: 2023-08-30 10:24:20.743740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad8c2163afc'
down_revision = '6ce07f19623f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_interfaces', 'folio_data_import_processing_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_interfaces', 'folio_data_import_processing_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
