"""Increase length of vendor_file.dag_run_id

Revision ID: a54c17f1dd1b
Revises: 82368e89d0cb
Create Date: 2023-05-19 12:00:03.417417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54c17f1dd1b'
down_revision = '82368e89d0cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_files', 'dag_run_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.VARCHAR(length=350),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_files', 'dag_run_id',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
