"""expected-load-time

Revision ID: a634337e2c85
Revises: bdc18b238b0c
Create Date: 2023-05-31 17:25:16.191037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a634337e2c85'
down_revision = 'bdc18b238b0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_files', sa.Column('expected_load_time', sa.DateTime(), nullable=True))
    op.drop_column('vendor_files', 'expected_execution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_files', sa.Column('expected_execution', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('vendor_files', 'expected_load_time')
    # ### end Alembic commands ###
