"""Add vendor interface removed field

Revision ID: acb1395e79ee
Revises: e7856548573b
Create Date: 2023-06-01 17:15:21.701588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb1395e79ee'
down_revision = 'e7856548573b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_interfaces', sa.Column('removed_from_folio', sa.Boolean(), nullable=True))
    op.execute('UPDATE vendor_interfaces SET removed_from_folio = false')
    op.alter_column('vendor_interfaces', 'removed_from_folio', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_interfaces', 'removed_from_folio')
    # ### end Alembic commands ###
