"""Rename expected load time to processing time

Revision ID: b09e821d201c
Revises: b812c8abeaf3
Create Date: 2023-06-12 10:57:38.304989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b09e821d201c'
down_revision = 'b812c8abeaf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_files', 'expected_load_time', nullable=True, new_column_name='expected_processing_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_files', 'expected_processing_time', nullable=True, new_column_name='expected_load_time')
    # ### end Alembic commands ###
