"""Add Folio job execution UUID column to VendorFile model

Revision ID: bdc18b238b0c
Revises: 9671879df3f4
Create Date: 2023-05-26 11:02:15.816067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc18b238b0c'
down_revision = '9671879df3f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_files', sa.Column('folio_job_execution_uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_files', 'folio_job_execution_uuid')
    # ### end Alembic commands ###
