"""Adds additional_email_recipients to VendorInterface model

Revision ID: e10a4aec20a9
Revises: 910e6f44a08e
Create Date: 2025-11-19 11:33:41.465441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10a4aec20a9'
down_revision = '910e6f44a08e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_interfaces', sa.Column('additional_email_recipients', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_interfaces', 'additional_email_recipients')
    # ### end Alembic commands ###
