"""Remove folio_interface_uuid uniqueness constraint

Revision ID: e7856548573b
Revises: 2c3487e0cac6
Create Date: 2023-06-01 16:51:43.346916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7856548573b'
down_revision = '2c3487e0cac6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendor_interfaces_folio_interface_uuid_key', 'vendor_interfaces', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vendor_interfaces_folio_interface_uuid_key', 'vendor_interfaces', ['folio_interface_uuid'])
    # ### end Alembic commands ###
