"""delete from argo column

Revision ID: 3ba541982292
Revises: 46e6a9bb59d0
Create Date: 2024-09-16 15:31:46.666579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba541982292'
down_revision: Union[str, None] = '46e6a9bb59d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_bookplates', sa.Column('deleted_from_argo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digital_bookplates', 'deleted_from_argo')
    # ### end Alembic commands ###
