"""Rename to fund_name

Revision ID: 46e6a9bb59d0
Revises: a0ad7b351d39
Create Date: 2024-09-11 16:05:43.679552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e6a9bb59d0'
down_revision: Union[str, None] = 'a0ad7b351d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_bookplates', sa.Column('fund_name', sa.String(), nullable=True))
    op.drop_constraint('digital_bookplates_name_key', 'digital_bookplates', type_='unique')
    op.create_unique_constraint(None, 'digital_bookplates', ['fund_name'])
    op.drop_column('digital_bookplates', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_bookplates', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'digital_bookplates', type_='unique')
    op.create_unique_constraint('digital_bookplates_name_key', 'digital_bookplates', ['name'])
    op.drop_column('digital_bookplates', 'fund_name')
    # ### end Alembic commands ###
