"""Adds fund_uuid column to digital_bookplates table

Revision ID: 61bd8c901b49
Revises: 3ba541982292
Create Date: 2024-10-03 10:47:52.139700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bd8c901b49'
down_revision: Union[str, None] = '3ba541982292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digital_bookplates', sa.Column('fund_uuid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'digital_bookplates', ['fund_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digital_bookplates', type_='unique')
    op.drop_column('digital_bookplates', 'fund_uuid')
    # ### end Alembic commands ###
